void main() {
  String ilce = "Kepez";
  String kita = "Asya";
  int faks = 2125551212;
  String posta_kodu = "07090";
  String insta_adresi = "https://www.instagram.com/";
  String calistigin_bolum = "Bilgisayar Programcılığı";
  int urun_miktari = 300;
  String musteri_soyadi = "Çetin";
  double odeme_miktari = 800.99;
  String dogum_tarihi = "18/02/2002";
  int borc = 999;
  String medeni_hal = "Bekar";
  String video_yorumu = "Çok açıklayıcı bir video";
  String odeme_saati = "12:24";
  int eft_miktari= 500000;
  int satilan_miktar = 37;
  String telefon_modeli = "Samsung Galaxy S21";
  String dergi_adi ="KAFKAOKUR";
  String basim_tarihi = "Eylül 2017";
  double zam_miktari = 49.35;
  int daire_sayisi = 124;
  int enlem = 32;
  int boylam = 39;
  String yemek_adi = "Pilav";
  double urun_fiyati = 89.99;
  String sirket = "Arenatürk";
  String video_adi = "Flutter Bootcamp Programı";
  double muzik_suresi = 2.56;
  int mekan_puani = 5;
  String dosya_adi = "ödev1";
  String resim_formati = "jpg";
  String renk = "Mavi";
  int renk_kodu = 120802 ;
  String bilgisayar_modeli = "Monster Abra A5";
  double ekran_boyutu = 15.5;
  int kullanim_suresi = 2;
  int basinc = 4;
  String etkinlik_gunu = "13 Temmuz Cumartesi";
  String odeme_gunu = "Pazartesi";
  String yolculuk_cikis_tarihi = "04/12/2024";
  String mahalle_adi = "Güneş";
  String otobus_hatti = "Sarısı";
  int kullanilan_dakika = 47;
  int kargo_takip_no = 67926523012;
  int kupon_suresi = 65;
  String kupon_kodu = "BA2435ASL12";
  String fatura_tarihi = "23/09/2016";


  print("İlçe : $ilce");
  print("Kıta : $kita");
  print("Faks : $faks");
  print("Posta Kodu : $posta_kodu");
  print("instagram Adresi : $insta_adresi");
  print("Çalıştığım Bölüm : $calistigin_bolum");
  print("Ürün Miktarı : $urun_miktari adet");
  print("Müşteri Soyadı : $musteri_soyadi");
  print("Ödeme Miktarı : $odeme_miktari₺");
  print("Doğum Tarihi : $dogum_tarihi");
  print("Borç : $borc₺");
  print("Medeni Hali : $medeni_hal");
  print("Video Yorumu : $video_yorumu");
  print("Ödeme Saati : $odeme_saati");
  print("Eft Miktarı : $eft_miktari₺");
  print("Satılan Miktar : %$satilan_miktar");
  print("Telefon Modeli : $telefon_modeli");
  print("Dergi Adı : $dergi_adi");
  print("Basım Tarihi : $basim_tarihi");
  print("Zam Miktarı : %$zam_miktari");
  print("Daire Sayısı : $daire_sayisi");
  print("Enlem : $enlem°");
  print("Boylam : $boylam°");
  print("Yemek Adı : $yemek_adi");
  print("Ürün Fiyatı : $urun_fiyati₺");
  print("Şirket : $sirket");
  print("Video Adı : $video_adi");
  print("Müzik Süresi : $muzik_suresi dk");
  print("Mekan Puanı : $mekan_puani");
  print("Dosya Adı : $dosya_adi");
  print("Resim Formatı : $resim_formati");
  print("Renk: $renk");
  print("Renk Kodu : $renk_kodu");
  print("Bilgisayar Modeli : $bilgisayar_modeli");
  print("Ekran Boyutu : $ekran_boyutu inç");
  print("Kullanım Süresi : $kullanim_suresi gün");
  print("Basınç : $basinc P");
  print("Etkinlik Günü : $etkinlik_gunu");
  print("Ödeme Günü : $odeme_gunu");
  print("Yolculuk Çıkış Tarihi : $yolculuk_cikis_tarihi");
  print("Mahalle Adı : $mahalle_adi");
  print("Otobüs Hattı : $otobus_hatti");
  print("Kullanılan Dakika  : $kullanilan_dakika dk");
  print("Kargo Takip No : $kargo_takip_no");
  print("Kupon Süresi : $kupon_suresi gün");
  print("Kupon Kodu : $kupon_kodu");
  print("Fatura Tarihi : $fatura_tarihi");

}